// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5uI0J1f1bcNWRNgEBXTTO1PjGfLqKJR8',
    appId: '1:267946891143:web:236cb9a2d50ab5f6bde522',
    messagingSenderId: '267946891143',
    projectId: 'laundry-c08d7',
    authDomain: 'laundry-c08d7.firebaseapp.com',
    storageBucket: 'laundry-c08d7.firebasestorage.app',
    measurementId: 'G-FFVYR8Z3J8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: 'YOUR_ANDROID_APP_ID',
    messagingSenderId: '267946891143',
    projectId: 'laundry-c08d7',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_iOS_API_KEY',
    appId: 'YOUR_iOS_APP_ID',
    messagingSenderId: '267946891143',
    projectId: 'laundry-c08d7',
    iosBundleId: 'com.example.laundry.laundry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_macOS_API_KEY',
    appId: 'YOUR_macOS_APP_ID',
    messagingSenderId: '267946891143',
    projectId: 'laundry-c08d7',
    iosBundleId: 'com.example.laundry.laundry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY',
    appId: 'YOUR_WINDOWS_APP_ID',
    messagingSenderId: '267946891143',
    projectId: 'laundry-c08d7',
  );
}